In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2
from PIL import Image
%matplotlib inline

In [3]:
import pickle

In [4]:
df = pickle.load(open('./data/dataframe_images_100_100.pickle', 'rb'))

In [5]:
df.head()

,gender,0,1,2,3,4,5,6,7,8,...,9990,9991,9992,9993,9994,9995,9996,9997,9998,9999
0,male,98,104,114,121,124,135,147,154,156,...,132,135,139,146,151,152,148,145,147,148
1,male,20,24,27,29,29,31,21,23,29,...,38,32,25,22,32,25,19,20,32,48
2,male,69,63,64,69,69,55,73,77,71,...,184,183,183,184,184,187,188,189,190,189
3,male,136,135,134,133,132,123,130,147,147,...,107,109,110,112,116,113,111,109,110,112
4,male,75,75,75,75,75,75,75,75,75,...,70,68,66,61,50,52,64,67,61,50

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 450 entries, 0 to 489
Columns: 10001 entries, gender to 9999
dtypes: object(1), uint8(10000)
memory usage: 4.3+ MB

In [7]:
df.isnull().sum()

gender    0
0         0
1         0
2         0
3         0
         ..
9995      0
9996      0
9997      0
9998      0
9999      0
Length: 10001, dtype: int64

In [9]:
df.dropna(axis=0, inplace=True)

In [13]:
X = df.iloc[:,1:]
y = df.iloc[:,0]

In [14]:
X.shape

(450, 10000)

In [15]:
y.shape

(450,)

In [22]:
Xnorm = X/X.max()

In [23]:
Xnorm

,0,1,2,3,4,5,6,7,8,9,...,9990,9991,9992,9993,9994,9995,9996,9997,9998,9999
0,0.384314,0.407843,0.447059,0.474510,0.486275,0.529412,0.578740,0.606299,0.611765,0.603922,...,0.517647,0.529412,0.545098,0.572549,0.592157,0.596078,0.580392,0.568627,0.576471,0.580392
1,0.078431,0.094118,0.105882,0.113725,0.113725,0.121569,0.082677,0.090551,0.113725,0.117647,...,0.149020,0.125490,0.098039,0.086275,0.125490,0.098039,0.074510,0.078431,0.125490,0.188235
2,0.270588,0.247059,0.250980,0.270588,0.270588,0.215686,0.287402,0.303150,0.278431,0.247059,...,0.721569,0.717647,0.717647,0.721569,0.721569,0.733333,0.737255,0.741176,0.745098,0.741176
3,0.533333,0.529412,0.525490,0.521569,0.517647,0.482353,0.511811,0.578740,0.576471,0.443137,...,0.419608,0.427451,0.431373,0.439216,0.454902,0.443137,0.435294,0.427451,0.431373,0.439216
4,0.294118,0.294118,0.294118,0.294118,0.294118,0.294118,0.295276,0.295276,0.294118,0.294118,...,0.274510,0.266667,0.258824,0.239216,0.196078,0.203922,0.250980,0.262745,0.239216,0.196078
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485,0.109804,0.113725,0.156863,0.070588,0.117647,0.098039,0.070866,0.125984,0.321569,0.505882,...,0.219608,0.254902,0.250980,0.274510,0.313725,0.443137,0.533333,0.450980,0.466667,0.466667
486,0.658824,0.658824,0.666667,0.654902,0.682353,0.690196,0.700787,0.704724,0.729412,0.698039,...,0.933333,0.909804,0.909804,0.921569,0.952941,0.901961,0.811765,0.858824,0.952941,0.458824
487,0.015686,0.035294,0.019608,0.113725,0.160784,0.321569,0.118110,0.165354,0.203922,0.290196,...,0.039216,0.035294,0.019608,0.035294,0.019608,0.019608,0.019608,0.019608,0.019608,0.019608
488,0.917647,0.917647,0.921569,0.921569,0.921569,0.921569,0.925197,0.925197,0.921569,0.917647,...,0.231373,0.317647,0.482353,0.447059,0.588235,0.211765,0.643137,0.854902,0.843137,0.890196
489,0.015686,0.015686,0.015686,0.015686,0.015686,0.015686,0.015748,0.015748,0.015686,0.015686,...,0.047059,0.047059,0.047059,0.050980,0.054902,0.058824,0.058824,0.058824,0.058824,0.062745

In [25]:
y_norm = np.where(y == 'female', 1, 0)

In [26]:
y_norm

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [28]:
np.savez('./data/data_100_100_norm.npz', Xnorm, y_norm)